In [50]:
import torch

In [5]:
#### 不同維度
print(torch.empty(3))
print(torch.empty(3,2))

tensor([-6.6382e+37,  4.5914e-41,  0.0000e+00])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [11]:
#### 類似 numpy 的函數
print(torch.rand(2))
print(torch.zeros(2))
print(torch.ones(2))
print(torch.ones(2,2,dtype=torch.float16))

tensor([0.9063, 0.9143])
tensor([0., 0.])
tensor([1., 1.])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [15]:
#### 特性
x = torch.ones(2,3,dtype=torch.int)
print(type(x))
print(x.dtype)
print(x.size())

<class 'torch.Tensor'>
torch.int32
torch.Size([2, 3])


In [16]:
#### 創建張量
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [31]:
#### 張量加減乘除
x = torch.rand(3,2)
y = torch.rand(3,2)
print(x+y)
print(x-y)
print(x/y)
print(x*y)

tensor([[0.7932, 1.8958],
        [1.2445, 1.7332],
        [1.0849, 0.4181]])
tensor([[-0.0271,  0.0577],
        [-0.0457,  0.2358],
        [-0.6951, -0.0591]])
tensor([[0.9340, 1.0628],
        [0.9292, 1.3149],
        [0.2190, 0.7525]])
tensor([[0.1571, 0.8977],
        [0.3867, 0.7371],
        [0.1735, 0.0428]])


In [20]:
#### 張量取值
print(x)
print(x[1,:])
print(x[2,1])
print(x[2,1].item())

tensor([[0.6133, 0.6513],
        [0.6618, 0.2460],
        [0.3161, 0.9323]])
tensor([0.6618, 0.2460])
tensor(0.9323)
0.9322500824928284


In [23]:
#### reshape
print(x.view(6))
print(x.view(2,3))
print(x.view(-1,3))

tensor([0.6133, 0.6513, 0.6618, 0.2460, 0.3161, 0.9323])
tensor([[0.6133, 0.6513, 0.6618],
        [0.2460, 0.3161, 0.9323]])
tensor([[0.6133, 0.6513, 0.6618],
        [0.2460, 0.3161, 0.9323]])


In [27]:
'''
numpy array 轉換
注意：若在 CPU 的環境，是共享記憶體的，所以改變了某變數，可能改變了另一變數如下
'''
#### 情境一：
print('情境一：')
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

#### 情境二：
print('情境二：')
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

情境一：
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
情境二：
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
'''
若想在 GPU 上做運算
或是換回在 CPU 上做運算
BTW numpy 僅能在 CPU 運算
'''
if torch.cuda.is_available():
    device = torch.device('cuda')
    # 法一
    x = torch.ones(5, device=device)
    # 法二
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to('cpu')

In [41]:
'''
宣告張量未來要算梯度
'''
x = torch.randn(5, requires_grad=True)
print(x)
print(x.grad)
y = x+2
print(y)
z = y*y*2
print(z)
z = z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

tensor([ 0.6567,  1.2497, -0.5861,  0.2293, -0.0113], requires_grad=True)
None
tensor([2.6567, 3.2497, 1.4139, 2.2293, 1.9887], grad_fn=<AddBackward0>)
tensor([14.1164, 21.1211,  3.9980,  9.9392,  7.9101], grad_fn=<MulBackward0>)
tensor(11.4170, grad_fn=<MeanBackward0>)
tensor([2.1254, 2.5998, 1.1311, 1.7834, 1.5910])


In [45]:
a = x.detach()
print(x)
print(a)

tensor([ 0.6567,  1.2497, -0.5861,  0.2293, -0.0113], requires_grad=True)
tensor([ 0.6567,  1.2497, -0.5861,  0.2293, -0.0113])


In [49]:
'''
關於梯度，小範例
'''
print('會記住之前的梯度:')
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    print(f'model_output:{model_output}')
    model_output.backward()
    print(weights.grad)

print('','將梯度歸零重新計算:', sep='\n')
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    print(f'model_output:{model_output}')
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

Situation 1:
model_output:12.0
tensor([3., 3., 3., 3.])
model_output:12.0
tensor([6., 6., 6., 6.])
model_output:12.0
tensor([9., 9., 9., 9.])

Situation 2:
model_output:12.0
tensor([3., 3., 3., 3.])
model_output:12.0
tensor([3., 3., 3., 3.])
model_output:12.0
tensor([3., 3., 3., 3.])
